config/routes.rb
HackerNewsRails::Application.routes.draw do
  get "welcome/index"

  resources :users 
  resources :posts

  resources :user_sessions
  get '/login' => "user_sessions#create"

 root to: "welcome#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :post_id, :user_id

  belongs_to :user
  belongs_to :post

  validates_presence_of :content
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title, :user_id
  
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password
  

  include BCrypt

  has_many :posts
  has_many :comments

  validates_presence_of :email
  validates_presence_of :password

  has_secure_password


  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new

  end

  def index
    @user = User.find(session[:user_id])
    @posts = @user.posts
    @comments = @user.comments
  end

  def show
    params.inspect
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.create(params[:post])
    @user = User.find(session[:user_id])
    @user.posts << @post
    redirect_to posts_path
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  #login
  def create
    @user = User.find_by_email(params[:user][:email])

    if @user
      session[:user_id] = @user.id
      redirect_to posts_path
      # @user = User.authenticate(params[:user][:password])
    else
      @error = "Your password or username is invalid, please sign up if you don't have an account."
      render welcome_index_path
    end
  end

  def destroy
    unless session[:user_id] = nil
      session[:user_id] = nil
    end
    redirect_to welcome_index_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new

  end

  def create
    @user = User.create(params[:user])

    if @user.valid?
      redirect_to welcome_index_path
    # session[:user_id] = @user.id
    # redirect_to posts_path
  else
    @error = "You can't leave the email or password form fields blank. Please submit your registration again."
    render 'login'
  end
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<nav><%= link_to "Logout", user_session_path(@user), method: :delete %></nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerNewsRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if session[:user_id] != nil %>
  <%= render "layouts/navbar" %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>Your Posts</h1>

<%= link_to "New Post", :controller => "posts", :action => "new"  %>

<% @posts.each do |post| %>
  <li style="list-style:none;"><%= link_to post.title, :controller => "posts", :action => "show", :id => post.id %></li><br>
<% end %>

<h1>Your Comments</h1>

<% @comments.each do |comment| %>
  <li style="list-style:none;"> <%= comment.content %></li>
<% end %>

<%= %>

app/views/posts/new.html.erb
<div style="margin-left:40%;">
<%= form_for :post, url: posts_path do |f|%>

  Title:
  <%= f.text_field :title, :placeholder => "Your title goes here"%><br>
<br>
<%= f.label :Content %><br>
<%= f.text_area :content %><br>
<%= f.submit :Post %>

<% end %>
</div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content%></p>
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
<p><%= comment.content %></p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up Below</h1>

<div style="margin: 0 auto;">
  <%= form_for :user, url: users_path do |f| %>
  <%= f.label :EMAIL %>
  <%= f.text_field :email %><br>
  <%= f.label :PASSWORD %>
  <%= f.text_field :password %>
  <%= f.submit :SIGNUP %>
  <%end%>
</div>

<% unless @error.nil? %>
<p><%= @error %></p>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>

<%= form_for :user, url: user_sessions_path do |f|%>
  <P>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.submit :SUBMIT%>
  </p>
<% end %>

<% unless @error.nil? %>
<p><%= @error %></p><br>
<h3>Create a new account:</h3>
<%= link_to "Creat Account", :controller => "users", :action => "new" %>%>
<% end %>